services:
  kade-drive:
    build: .
    image: kade-drive
    stdin_open: true
    tty: true
    ports:
      - '8085:8085'
      - '50001:50001'
    networks:
      - kade-drive-network
      - default

networks:
  kade-drive-network:
    driver: bridge
