site_name: Kade Drive DHT
docs_dir: ../../docs/es/
site_dir: ../../generated/es

theme:
  highlightjs: true
  hljs_languages:
        - Python
        - Console
  language: es
  custom_dir: ../../overrides
  favicon: assets/images/favicon.ico
  name: material

extra:
  alternate:
    - name: English
      link: docs/docs/en/index.md
      lang: en
    - name: Español
      link: docs/docs/es/index.md
      lang: es
    # Add more lang
plugins:
  - search:                                         
      lang: es


nav:
  - introduccion: index.md
  - instalación: instalacion.md
  - ejemplos: ejemplos.md
  - descripcion: descripcion.md
  - persistencia: persistencia.md
  - cliente: cliente.md
  - autodescubrimiento: autodescubrimiento.md
  - replicacion: replicacion.md
  - tolerancia-fallas: tolerancia-fallas.md
  - por-que-kademlia: por-que-kademlia.md
  - analisis-cap: analisis-cap.md
  - recomendaciones: recomendaciones.md
  - 
