site_name: Kade Drive DHT
theme: 
  highlightjs: true
  name: material
docs_dir: docs/docs/en

plugins:
  - search

extra:
  alternate:
    - name: English
      link: index.html
      lang: en
    - name: Español
      link: es/index.html
      lang: es
    # Add more languages as needed

# General configuration
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Additional configuration options
# ...

