site_name: Kade Drive DHT
docs_dir: ../../docs/en/
site_dir: ../../generated/en

theme:
  highlightjs: true
  hljs_languages:
        - Python
        - Console
  language: en
  custom_dir: ../../overrides
  favicon: assets/images/favicon.ico
  name: material

extra:
  alternate:
    - name: English
      link: docs/docs/en/index.md
      lang: en
    - name: Español
      link: docs/docs/es/index.md
      lang: es
    # Add more lang

plugins:
  - search:                                         
      lang: en 

nav:
  - 1 - Introduction: index.md
  - 1.1 - Installation: installation-setup.md
  - 1.2 - Examples: examples.md 
  - 2 - Description: description.md
  - 3 - Persistence: persistence.md
  - 4 - Client: client.md
  - 5 - Autodiscovery: autodiscovery.md
  - 6 - Replication: replication.md
  - 7 - Fault Tolerance: fault-tolerance.md
  - 8 - Why Kademlia: why-kademlia.md
  - 9 - CAP Theorem Analysis: cap-analysis.md
  - 10 - Recommendations: recommendations.md
